edit extension
EvgeniyDemid/niffler-st5 pull request #5
Opened 2024-05-31 17:21 UTC by EvgeniyDemid

2024-06-01 06:14 UTC, sashkir7 requested changes
Доброе утро! С первым летним днем!

Хорошая работа, но необходимо внести ряд правок:
1. Некоторые из методов по работе с БД имеют логические ошибки. Например, получение категории по ее наименованию. Нужно получать либо коллекцию, либо при фильтрации учитывать пользователя.
2. Некоторые из методов реализации написаны не совсем верно.
3. Работа с экземпляром Hibernate в extension-классе. Важно!

Более подобно описал в комментариях

2024-06-01 06:14 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/data/entity/UserAuthEntity.java
> +	public UserAuthEntity fromJson(UserJson userJson) {
Данный метод должен быть static. И вызываться не из экземпляра класса

2024-06-01 06:14 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/data/repository/SpendRepositoryHibernate.java
> +		em.remove(em.merge(category));
А зачем перед удалением делать merge?

2024-06-01 06:14 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/data/repository/SpendRepositoryHibernate.java
> +	}
Если мы знаем id категории, то username там не нужен
У каждой категории - свой идентификатор. И мы легко по нему можем найти и удалить нужную нам запись

2024-06-01 06:14 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/data/repository/SpendRepositoryHibernate.java
> +	}
В данной реализации никогда не вернется несколько трат - то есть полноценного списка не будет. Нужно изменить, чтобы возвращалась именно коллекция трат

2024-06-01 06:14 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/data/repository/SpendRepositoryHibernate.java
> +	}
`em.find(SpendEntity.class, username)` - вернет ОДИН объект

2024-06-01 06:14 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/data/repository/SpendRepositoryJdbc.java
> +	}
Хорошо бы реализовать данный метод
Также нужно учитывать, что может быть несколько трат по одной и той же категории. То есть метод должен возвращать коллекцию, а не один объект

2024-06-01 06:14 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/data/repository/SpendRepositoryStringJdbc.java
> +	}
Реализовать

2024-06-01 06:14 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/data/repository/UserRepository.java
>  		return new UserRepositoryJdbc();
Чтобы дважды не писать System.getProperty("repo") - можно сохранить в переменную

2024-06-01 06:14 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/data/repository/UserRepositoryHibernate.java
> +	}
Для чего передаем List<Authority> listAuthority?
1. Этот параметр нигде не используется.
2. Список прав у нас есть в UserAuthEntity - поле authorities

2024-06-01 06:14 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/extension/DbCategoryExtension.java
> +	private final SpendRepositoryHibernate srh = new SpendRepositoryHibernate();
Очень важный момент!!!

Важно понимать, что экземпляр Repository для работы с БД, созданный в extension, как свойство класса - будет существовать в ед. экземпляре НА ВСЕ ПОТОКИ тестов. Это связано с тем, что Junit создает ед. экземпляр extension-класса. Таким образом, при параллельном прогоне тестов могут наблюдаться проблемы (если мы работаем с Hibernate, тк для каждого потока - свой экземпляр)

2024-06-01 06:14 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/extension/DbSpendExtension.java
> +	private final SpendRepositoryHibernate srh = new SpendRepositoryHibernate();
Аналогично

2024-06-01 06:48 UTC, EvgeniyDemid commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/data/entity/UserAuthEntity.java
> +	public UserAuthEntity fromJson(UserJson userJson) {
Сделал метода staitc, вроде до этого мы всегда создавали метод в самом классе

2024-06-01 07:02 UTC, EvgeniyDemid commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/data/repository/SpendRepositoryHibernate.java
> +		em.remove(em.merge(category));
Если ее убрать то будет ошибка , не могу разобраться что не так , поэтому применил это решение , если такая реализация не допустима то буду исправлять .

2024-06-01 07:05 UTC, EvgeniyDemid commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/data/repository/SpendRepositoryHibernate.java
> +	}
Исправил реализацию , предположил что одна категория может принадлежать нескольким пользователям.

2024-06-01 07:15 UTC, EvgeniyDemid commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/data/repository/SpendRepositoryHibernate.java
> +	}
Исправил реализацию

2024-06-02 16:34 UTC, EvgeniyDemid commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/data/repository/SpendRepositoryJdbc.java
> +	}
Реализовал метод

2024-06-02 16:43 UTC, EvgeniyDemid commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/data/repository/SpendRepositoryStringJdbc.java
> +	}
готово

2024-06-02 16:47 UTC, EvgeniyDemid commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/data/repository/UserRepository.java
>  		return new UserRepositoryJdbc();
Создал переменную

2024-06-02 18:11 UTC, EvgeniyDemid commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/data/repository/UserRepositoryHibernate.java
> +	}
Исправил замечания

2024-06-02 18:28 UTC, EvgeniyDemid commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/extension/DbCategoryExtension.java
> +	private final SpendRepositoryHibernate srh = new SpendRepositoryHibernate();
Не совсем понял суть проблемы , но думаю с этим разберусь при выполнении следующего задания с параллельным запуском

2024-06-02 18:55 UTC, EvgeniyDemid commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/extension/DbCategoryExtension.java
> +	private final SpendRepositoryHibernate srh = new SpendRepositoryHibernate();
Вроде как разобрался , просьба проверить .

2024-06-04 06:53 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/data/entity/UserAuthEntity.java
> +	public UserAuthEntity fromJson(UserJson userJson) {
В чем смысл из экземпляра класса вызывать метод, который создает новый экземпляр класса?
Здесь как раз-таки нужен static - мы у самого класса (не его экземпляра) вызываем метод, который нам возвращает новый объект

2024-06-04 06:56 UTC, sashkir7 approved these changes

2024-06-04 06:56 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/extension/DbSpendExtension.java
> +	private final SpendRepositoryHibernate srh = (SpendRepositoryHibernate) SpendRepository.getInstance();
Приводить к SpendRepositoryHibernate не нужно
Можно (и нужно) 
private final SpendRepository spendRepository = SpendRepository.getInstance();

2024-06-04 06:56 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/extension/DbSpendExtension.java
> +	private final SpendRepositoryHibernate srh = (SpendRepositoryHibernate) SpendRepository.getInstance();
Что я пытался сказать: если мы работаем с Hibernate, то создавать свойство класса на уровне Extension-класса не нужно. Вызывать SpendRepository.getInstance() нужно в методе - тогда проблем при параллельном запуске тестов не будет

2024-06-05 17:12 UTC, merged